plugins {
    id 'java'
    id "io.github.goooler.shadow" version "8.1.8"
    id("xyz.jpenilla.run-paper") version "2.3.1"
}

group = 'me.elaineqheart'
version = '1.4.4'

repositories {
    mavenCentral()
    maven {
        name = "spigotmc-repo"
        url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven { url 'https://jitpack.io' }
    maven { url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/' }
    maven { url = 'https://repo.example.com/repository/maven-public/' }
}

//alt + ins
dependencies {
    compileOnly("org.spigotmc:spigot-api:1.21.4-R0.1-SNAPSHOT")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7")
    compileOnly("com.github.Unp1xelt:Locale-API:1.0")
    compileOnly("me.clip:placeholderapi:2.11.6")
    implementation("net.kyori:adventure-text-minimessage:4.26.1")
    implementation("net.kyori:adventure-text-serializer-legacy:4.26.1")
    implementation("net.kyori:adventure-platform-bukkit:4.3.4")
    implementation("de.rapha149.signgui:signgui:2.5.4")
    implementation("com.zaxxer:HikariCP:5.1.0")
    implementation("org.xerial:sqlite-jdbc:3.45.1.0")
}

tasks.named('jar') {
    enabled = true
}

tasks.named('shadowJar') {
    archiveBaseName.set(rootProject.name ?: 'AuctionHouse')
    archiveClassifier.set('')
    archiveVersion.set(version)
    mergeServiceFiles()
    
    // Relocate packages to avoid conflicts with other plugins
    relocate 'net.kyori', 'me.elaineqheart.auctionHouse.libs.kyori'
    relocate 'com.zaxxer.hikari', 'me.elaineqheart.auctionHouse.libs.hikari'
    relocate 'de.rapha149.signgui', 'me.elaineqheart.auctionHouse.libs.signgui'
}

tasks {
    runServer {
        // Configure the Minecraft version for our task.
        // This is the only required configuration besides applying the plugin.
        // Your plugin's jar (or shadowJar if present) will be used automatically.
        minecraftVersion("1.21")
    }
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
